frase = ('Agora com pagamento por boleto bancário')
print(frase[0:23:2])
print(len(frase))
print(frase.count('e'))
print(frase.find('cea'))
print('tka' in frase)
print(frase.replace('Agora com pagamento por boleto bancário', 'sorry, bro'))
print(frase.upper())
print('.|.'.join(frase))